server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/parknshop?characterEncoding=UTF-8&useSSL=false
    username: root
    password:
