server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://mysql:3306/parknshop?characterEncoding=UTF-8&useSSL=false
    username: root
    password:
  redis:
    host: redis
    port: 6379
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none